import { chromium } from '@playwright/test';
const browser = await chromium.launch({ args: ['--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:4173/', { waitUntil: 'load', timeout: 90000 });
await page.waitForTimeout(600);
await page.screenshot({ path: 'screenshots-verify/fx-rise.png' });
await page.waitForTimeout(5000);
await page.screenshot({ path: 'screenshots-verify/fx-settled.png' });
await browser.close();
console.log('ok');
